'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class BirthdayRpts
    Protected WithEvents RBcomp As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label26 As System.Web.UI.WebControls.Label
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator10 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RequiredFieldValidator11 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents showtTrainingReport As System.Web.UI.WebControls.Button
    Protected WithEvents sqlsect As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDesig As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlsecdept As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents cceto As AjaxControlToolkit.CalendarExtender
    Protected WithEvents ccefrom As AjaxControlToolkit.CalendarExtender
End Class
