'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class empmasterrpt
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents Label4 As System.Web.UI.WebControls.Label
    Protected WithEvents empno As System.Web.UI.WebControls.TextBox
    Protected WithEvents R1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents prinemp As System.Web.UI.WebControls.Button
End Class
