'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4971
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class OpeningStockEntry
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents ddlDepartment As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents dgvOpeningStock As System.Web.UI.WebControls.GridView
    Protected WithEvents btnSave As System.Web.UI.WebControls.Button
End Class
