'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class OTentryPayroll
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents frmdt As System.Web.UI.WebControls.Label
    Protected WithEvents vfd As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator10 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents todt As System.Web.UI.WebControls.Label
    Protected WithEvents vtd As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator11 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ecode As System.Web.UI.WebControls.Label
    Protected WithEvents code As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator14 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Show1 As System.Web.UI.WebControls.Button
    Protected WithEvents LblMsg As System.Web.UI.WebControls.Label
    Protected WithEvents lblto As System.Web.UI.WebControls.Label
    Protected WithEvents lblfrom As System.Web.UI.WebControls.Label
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents ccelf As AjaxControlToolkit.CalendarExtender
    Protected WithEvents ccelt As AjaxControlToolkit.CalendarExtender
End Class
