'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class OTentryCategory
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents frmdt As System.Web.UI.WebControls.Label
    Protected WithEvents otdate As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator10 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Otelig As System.Web.UI.WebControls.Label
    Protected WithEvents rb1 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents depart As System.Web.UI.WebControls.Label
    Protected WithEvents Deptddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents section As System.Web.UI.WebControls.Label
    Protected WithEvents Secddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lbletype As System.Web.UI.WebControls.Label
    Protected WithEvents emptyp2 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ecode As System.Web.UI.WebControls.Label
    Protected WithEvents code As System.Web.UI.WebControls.TextBox
    Protected WithEvents Show1 As System.Web.UI.WebControls.Button
    Protected WithEvents lbldt As System.Web.UI.WebControls.Label
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents LblMsg As System.Web.UI.WebControls.Label
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource3 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource5 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents GridView2 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource6 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents GridView3 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource7 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource8 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents ccelf As AjaxControlToolkit.CalendarExtender
    Protected WithEvents SqlDataSource9 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqldept As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource4 As System.Web.UI.WebControls.SqlDataSource
End Class
