'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class RptOTBudgetSetting
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator12 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator11 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Panel1 As System.Web.UI.WebControls.Panel
    Protected WithEvents RadioButtonList1 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents ddldeptr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlsectrpt As System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnshow As System.Web.UI.WebControls.Button
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents selsectreport As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents ccefrom As AjaxControlToolkit.CalendarExtender
    Protected WithEvents cceto As AjaxControlToolkit.CalendarExtender
End Class
