'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4959
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class Letterpage
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents ScriptManager1 As System.Web.UI.ScriptManager
    Protected WithEvents empcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents empname As System.Web.UI.WebControls.Label
    Protected WithEvents departmentcode As System.Web.UI.WebControls.Label
    Protected WithEvents sectioncode As System.Web.UI.WebControls.Label
    Protected WithEvents designation As System.Web.UI.WebControls.Label
    Protected WithEvents emptype As System.Web.UI.WebControls.Label
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents DropDownList1 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Button1 As System.Web.UI.WebControls.Button
    Protected WithEvents Button2 As System.Web.UI.WebControls.Button
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents PlaceHolder1 As System.Web.UI.WebControls.PlaceHolder
    Protected WithEvents UpdatePanel1 As System.Web.UI.UpdatePanel
    Protected WithEvents HtmlEditor1 As Winthusiasm.HtmlEditor.HtmlEditor
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
End Class
