'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class EditJS
    Protected WithEvents lblrecno As System.Web.UI.WebControls.Label
    Protected WithEvents lblempcode As System.Web.UI.WebControls.Label
    Protected WithEvents lblename As System.Web.UI.WebControls.Label
    Protected WithEvents lbldept As System.Web.UI.WebControls.Label
    Protected WithEvents lblsect As System.Web.UI.WebControls.Label
    Protected WithEvents lbldesig As System.Web.UI.WebControls.Label
    Protected WithEvents lblcode As System.Web.UI.WebControls.Label
    Protected WithEvents lblpurpose As System.Web.UI.WebControls.Label
    Protected WithEvents ValidationSummary1 As System.Web.UI.WebControls.ValidationSummary
    Protected WithEvents txtrevno As System.Web.UI.WebControls.Label
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents df As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents dff As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ccelt As AjaxControlToolkit.CalendarExtender
    Protected WithEvents ccelf As AjaxControlToolkit.CalendarExtender
    Protected WithEvents txtitem As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtkey As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Button1 As System.Web.UI.WebControls.Button
    Protected WithEvents lstgoal As System.Web.UI.WebControls.ListBox
    Protected WithEvents ImageButton1 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents sqlgoal As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents cbtechnical As System.Web.UI.WebControls.CheckBoxList
    Protected WithEvents sqltechnical As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents cbbehavior As System.Web.UI.WebControls.CheckBoxList
    Protected WithEvents SQLBEHAVIOUR As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents btnsave As System.Web.UI.WebControls.Button
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
