<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="GoalSetting.aspx.vb" Inherits="E_Management.GoalSetting" 
   %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">

<table cellpadding=0 cellspacing=0 align=center >
                    <tr>
                        <td style="width: 16px; height: 16px">
                            <IMG height="16" src="../../images/top_lef.gif" width="16"></td>
                        <td background="../../images/top_mid.gif" style="height: 16px; width: 807px;">
                            <IMG height="16" src="../../images/top_mid.gif"width="16"></td>
                        <td style="width: 24px; height: 16px;">
                            <IMG height="16" src="../../images/top_rig.gif" width="24"></td>
                    </tr>
                    <tr>
                        <td background="../../images/cen_lef.gif" style="width: 16px; height: 248px;">
                        <IMG height="11" src="../../images/cen_lef.gif" width="16"></td>
                        <td vAlign="top" bgColor="#ffffff" style="width: 807px">
                            <table style="background-color: beige">
                                <tr>
                                    <td class="td_head" colspan="2">
                                        GOAL SETTING</td>
                                </tr>
                                <tr>
                                    <td style="width: 168px">
                                        Goal Allignment No.</td>
                                    <td style="width: 406px">
                                        <asp:Label ID="lblsno" runat="server"></asp:Label></td>
                                </tr>
                                <tr>
                                    <td style="width: 168px">
                                        Goal allignment Description</td>
                                    <td style="width: 406px">
                                        <asp:TextBox ID="txtdesc" runat="server" TextMode="MultiLine" Width="328px"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtdesc"
                                            ErrorMessage="Enter Desc!!" ValidationGroup="ss"></asp:RequiredFieldValidator></td>
                                </tr>
                                <tr>
                                    <td colspan="2" style="height: 20px">
                                        <asp:Label ID="Label1" runat="server" Font-Size="Small" ForeColor="#C00000"></asp:Label></td>
                                </tr>
                                <tr>
                                    <td align="right" colspan="2" style="height: 19px">
                                        <asp:Button ID="btnSave" runat="server" SkinID="buttonskin1" Text="ADD" ValidationGroup="ss" /></td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                                            AutoGenerateEditButton="True" CellPadding="4" DataSourceID="sqlgoal" ForeColor="#333333"
                                            GridLines="Vertical" Width="100%" DataKeyNames="sno">
                                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                            <Columns>
                                                <asp:BoundField DataField="sno" HeaderText="sno" SortExpression="sno" ReadOnly=true  />
                                                <asp:BoundField DataField="goalalign" HeaderText="Goal allignment Description" SortExpression="goalalign" />
                                                  <asp:BoundField DataField="setby" HeaderText="GoalSetBy" SortExpression="sno" ReadOnly=true  />
                                            </Columns>
                                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                            <SelectedRowStyle BackColor="Blue" Font-Bold="True" ForeColor="#333333" />
                                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                            <EditRowStyle BackColor="#999999" />
                                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                        </asp:GridView>
                                        <asp:SqlDataSource ID="sqlgoal" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                                            SelectCommand="SELECT [goalalign], [sno],setby FROM [man_goalalign]"
                                             DeleteCommand = "delete from [man_goalalign] where sno=@sno" 
                                              UpdateCommandType="StoredProcedure" UpdateCommand = "hrmis_js_goalset">
                                               <UpdateParameters>
                                               <asp:Parameter Type="Int32"  Name= "sno" />
                                               <asp:Parameter Type="String" Name="goalalign" />
                                               <asp:Parameter Type="string" name= "setby" DefaultValue="014543" />
                                               </UpdateParameters>
                                       
                                              </asp:SqlDataSource>
                                               
                                    </td>
                                </tr>
                            </table>
                        
                        
                        
                        
                        </td>
                        <td background="../../images/cen_rig.gif" style="width: 25px; height: 248px;">
                        <IMG height="11" src="../../images/cen_rig.gif" width="24"></td>
                    </tr>
                    <tr>
                    <td width="16" height="16">
                        <IMG height="16" src="../../images/bot_lef.gif" width="16"></td>
                    <td background="../../images/bot_mid.gif" height="16" style="width: 807px">
                        <IMG height="16" src="../../images/bot_mid.gif" width="16"></td>
                    <td height="16" style="width: 25px">
                        <IMG height="16" src="../../images/bot_rig.gif" width="24"></td>
                </tr>
            </table>
</asp:Content>
