<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="jobcode.aspx.vb" Inherits="E_Management.jobcode" 
   %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">


<table cellpadding=0 cellspacing=0 width=100% >
                    <tr>
                        <td style="width: 16px; height: 16px">
                            <IMG height="16" src="../../images/top_lef.gif" width="16"></td>
                        <td background="../../images/top_mid.gif" style="height: 16px; width: 807px;">
                            <IMG height="16" src="../../images/top_mid.gif"width="16"></td>
                        <td style="width: 24px; height: 16px;">
                            <IMG height="16" src="../../images/top_rig.gif" width="24"></td>
                    </tr>
                    <tr>
                        <td background="../../images/cen_lef.gif" style="width: 16px; height: 248px;">
                        <IMG height="11" src="../../images/cen_lef.gif" width="16"></td>
                        <td vAlign="top" bgColor="#ffffff" style="width: 100%">
                            <table style="background-color: beige" border="1" cellpadding="1" cellspacing="1">
                                <tr>
                                    <td class="td_head" colspan="2">
                                        JOB CODE ASSIGNMENT</td>
                                    <td align="left" colspan="1" rowspan="10" valign="top">
                                        EXISTING JOB CODE<asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
                                            AutoGenerateColumns="False" CellPadding="4" DataKeyNames="departmentcode,designation"
                                            DataSourceID="sqljobcode" ForeColor="#333333" PageSize="15" Width="100%" AutoGenerateDeleteButton="True">
                                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                            <Columns>
                                                <asp:BoundField DataField="departmentcode" HeaderText="Departmentcode" SortExpression="departmentcode" />
                                                <asp:BoundField DataField="designation" HeaderText="Designation" SortExpression="designation" />
                                                <asp:BoundField DataField="jobcode" HeaderText="Jobcode" SortExpression="jobcode" />
                                            </Columns>
                                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                            <EditRowStyle BackColor="#999999" />
                                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                        </asp:GridView>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="td_head" colspan="2">
                                        <asp:Label ID="lblerr" runat="server" Font-Size="Small" ForeColor="#C00000"></asp:Label></td>
                                </tr>
                                <tr>
                                    <td>
                                        Select Department</td>
                                    <td>
                                        <asp:DropDownList ID="ddldept" runat="server" AppendDataBoundItems="True" AutoPostBack="True"
                                            DataSourceID="sqldept" DataTextField="Column1" DataValueField="departmentcode" Width="300px">
                                            <asp:ListItem Selected="True" Value="-1">--Select--</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" InitialValue="-1"  runat="server" ControlToValidate="ddldept"
                                            ErrorMessage="Select Department!!"></asp:RequiredFieldValidator></td>
                                </tr>
                                <tr>
                                    <td style="height: 12px">
                                        Select Designation</td>
                                    <td>
                                        <asp:DropDownList ID="ddldesig" runat="server" AppendDataBoundItems="True" AutoPostBack="True"
                                            DataSourceID="sqldesig" DataTextField="designationname" DataValueField="designationname" Width="300px">
                                            <asp:ListItem Selected="True" Value="-1">--Select--</asp:ListItem>
                                        </asp:DropDownList><asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="ddldesig"
                                            ErrorMessage="Select Section!!" InitialValue="-1" ></asp:RequiredFieldValidator></td>
                                </tr>
                                <tr>
                                    <td>
                                        Enter Job code</td>
                                    <td>
                                        <asp:TextBox ID="txtcode" runat="server" Width="117px"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtcode"
                                            ErrorMessage="Enter Jobcode"></asp:RequiredFieldValidator></td>
                                </tr>
                                <tr>
                                    <td style="height: 6px; background-color: #cccc66;">
                                        Select Behaviour</td>
                                    <td style="height: 6px; background-color: #cccc66">
                                        Select Technical Skills</td>
                                </tr>
                                <tr>
                                    <td style="width: 250px" align="left" valign="top">
                                        <asp:CheckBoxList ID="cbbehaviour" runat="server" DataSourceID="SqlDataSource2"
                                            DataTextField="skill" DataValueField="skill" RepeatColumns="2" RepeatDirection="Horizontal">
                                        </asp:CheckBoxList></td>
                                    <td align="left" valign="top">
                                        <asp:CheckBoxList ID="cbtechnical" runat="server" DataSourceID="SqlDataSource1"
                                            DataTextField="skill" DataValueField="skill" RepeatColumns="2" RepeatDirection="Horizontal">
                                        </asp:CheckBoxList></td>
                                </tr>
                                <tr>
                                    <td align="left" colspan="2">
                                        </td>
                                </tr>
                                <tr>
                                    <td align="right" colspan="2">
                                        &nbsp;<asp:Button ID="btnsave" runat="server" SkinID="buttonskin1" Text="SAVE" /></td>
                                </tr>
                                <tr>
                                    <td align="left" colspan="2">
                                        &nbsp;
                                    </td>
                                </tr>
                            </table>
                            <asp:SqlDataSource ID="sqldept" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                                SelectCommand="select departmentcode +'-'+departmentname ,departmentcode from department order by departmentcode">
                            </asp:SqlDataSource>
                            <asp:SqlDataSource ID="sqldesig" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                                SelectCommand="SELECT [designationname] FROM [designation] ORDER BY [designationname]">
                            </asp:SqlDataSource>
                                        <asp:SqlDataSource ID="sqljobcode" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                                            SelectCommand="SELECT [departmentcode], [designation], [jobcode] FROM [man_jobcode]"
                                             DeleteCommand ="delete from man_jobcode where departmentcode=@departmentcode and designation=@designation">
                                        </asp:SqlDataSource>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                                SelectCommand="SELECT DISTINCT [skill] FROM [man_skillmatch] WHERE ([skilltitle] = @skilltitle) ORDER BY [skill]">
                                <SelectParameters>
                                    <asp:Parameter DefaultValue="Technical Skill" Name="skilltitle" Type="String" />
                                </SelectParameters>
                            </asp:SqlDataSource>
                        
                    
                    
                    
                        </td>
                        <td background="../../images/cen_rig.gif" style="width: 25px; height: 248px;">
                        <IMG height="11" src="../../images/cen_rig.gif" width="24"></td>
                    </tr>
                    <tr>
                    <td width="16" height="16">
                        <IMG height="16" src="../../images/bot_lef.gif" width="16"></td>
                    <td background="../../images/bot_mid.gif" height="16" style="width: 807px">
                        <IMG height="16" src="../../images/bot_mid.gif" width="16"></td>
                    <td height="16" style="width: 25px">
                        <IMG height="16" src="../../images/bot_rig.gif" width="24"></td>
                </tr>
            </table>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
        SelectCommand="SELECT DISTINCT [skill] FROM [man_skillmatch] WHERE ([skilltitle] = @skilltitle) ORDER BY [skill]">
        <SelectParameters>
            <asp:Parameter DefaultValue="Behavior" Name="skilltitle" Type="String" />
        </SelectParameters>
    </asp:SqlDataSource>
</asp:Content>
