'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class jobPurposeSetting
    Protected WithEvents txtempcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents lblename As System.Web.UI.WebControls.Label
    Protected WithEvents lbldept As System.Web.UI.WebControls.Label
    Protected WithEvents lblsect As System.Web.UI.WebControls.Label
    Protected WithEvents lbldesig As System.Web.UI.WebControls.Label
    Protected WithEvents lblcode As System.Web.UI.WebControls.Label
    Protected WithEvents lblpurpose As System.Web.UI.WebControls.Label
    Protected WithEvents txtpurpose As System.Web.UI.WebControls.TextBox
    Protected WithEvents chbsave As System.Web.UI.WebControls.CheckBox
    Protected WithEvents btnsave As System.Web.UI.WebControls.Button
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents sqlpurpose As System.Web.UI.WebControls.SqlDataSource
End Class
