'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class Employeesearch
    Protected WithEvents ddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Label As System.Web.UI.WebControls.Label
    Protected WithEvents keyin As System.Web.UI.WebControls.TextBox
    Protected WithEvents lblgender As System.Web.UI.WebControls.Label
    Protected WithEvents gnder As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblforeign As System.Web.UI.WebControls.Label
    Protected WithEvents forn As System.Web.UI.WebControls.DropDownList
    Protected WithEvents errmsg As System.Web.UI.WebControls.Label
    Protected WithEvents search As System.Web.UI.WebControls.Button
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
End Class
