'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class exitinterviewreport
    Protected WithEvents empcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents cb1 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents Label26 As System.Web.UI.WebControls.Label
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents ccefrom As AjaxControlToolkit.CalendarExtender
    Protected WithEvents cceto As AjaxControlToolkit.CalendarExtender
    Protected WithEvents showrepOT As System.Web.UI.WebControls.Button
End Class
