'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class exitinterview
    Protected WithEvents datetoday As System.Web.UI.WebControls.Label
    Protected WithEvents empcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents empname As System.Web.UI.WebControls.Label
    Protected WithEvents section As System.Web.UI.WebControls.Label
    Protected WithEvents department As System.Web.UI.WebControls.Label
    Protected WithEvents cb1 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb2 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb3 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb4 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb5 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb6 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb7 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb8 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb9 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb10 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cb11 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents others As System.Web.UI.WebControls.TextBox
    Protected WithEvents likeleast As System.Web.UI.WebControls.TextBox
    Protected WithEvents deptenv As System.Web.UI.WebControls.TextBox
    Protected WithEvents barriers As System.Web.UI.WebControls.TextBox
    Protected WithEvents supervisor As System.Web.UI.WebControls.TextBox
    Protected WithEvents peers As System.Web.UI.WebControls.TextBox
    Protected WithEvents subordinates As System.Web.UI.WebControls.TextBox
    Protected WithEvents comments As System.Web.UI.WebControls.TextBox
    Protected WithEvents rb1 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents uniformdate As System.Web.UI.WebControls.TextBox
    Protected WithEvents save As System.Web.UI.WebControls.Button
    Protected WithEvents CalendarExtender1 As AjaxControlToolkit.CalendarExtender
End Class
