'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class jobapplication2malay
    Protected WithEvents sch1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents highpass1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents joined1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents left1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents sch2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents highpass2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents joined2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents left2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents sch3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents highpass3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents joined3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents left3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents sch4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents highpass4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents joined4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents left4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents sports As System.Web.UI.WebControls.TextBox
    Protected WithEvents cmpny1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cphone1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cdate1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents ctitle1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cduties1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents csalary1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents reason1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cmpny2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cphone2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cdate2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents ctitle2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cduties2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents csalary2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents reason2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cmpny3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cphone3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cdate3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents ctitle3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cduties3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents csalary3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents reason3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cmpny4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cphone4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cdate4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents ctitle4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cduties4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents csalary4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents reason4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents Button2 As System.Web.UI.WebControls.Button
    Protected WithEvents savenxt As System.Web.UI.WebControls.Button
    Protected WithEvents Calendar1 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar2 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar3 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar4 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar5 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar6 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar7 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar8 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar9 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar10 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Calendar11 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents calendar12 As AjaxControlToolkit.CalendarExtender
End Class
