'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class jobapplicationmalay
    Protected WithEvents applno As System.Web.UI.WebControls.Label
    Protected WithEvents datetoday As System.Web.UI.WebControls.Label
    Protected WithEvents ddldesig As System.Web.UI.WebControls.DropDownList
    Protected WithEvents name As System.Web.UI.WebControls.TextBox
    Protected WithEvents icnew As System.Web.UI.WebControls.TextBox
    Protected WithEvents icold As System.Web.UI.WebControls.TextBox
    Protected WithEvents address As System.Web.UI.WebControls.TextBox
    Protected WithEvents mobile As System.Web.UI.WebControls.TextBox
    Protected WithEvents iccolor As System.Web.UI.WebControls.DropDownList
    Protected WithEvents sex As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents phone As System.Web.UI.WebControls.TextBox
    Protected WithEvents nationality As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents epf As System.Web.UI.WebControls.TextBox
    Protected WithEvents socso As System.Web.UI.WebControls.TextBox
    Protected WithEvents tax As System.Web.UI.WebControls.TextBox
    Protected WithEvents dob As System.Web.UI.WebControls.TextBox
    Protected WithEvents age As System.Web.UI.WebControls.TextBox
    Protected WithEvents lang As System.Web.UI.WebControls.TextBox
    Protected WithEvents race As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator5 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents religion As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents marital As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator6 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents country As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator4 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents blood As System.Web.UI.WebControls.TextBox
    Protected WithEvents relationship As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator7 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents rname As System.Web.UI.WebControls.TextBox
    Protected WithEvents ricold As System.Web.UI.WebControls.TextBox
    Protected WithEvents ricnew As System.Web.UI.WebControls.TextBox
    Protected WithEvents rage As System.Web.UI.WebControls.TextBox
    Protected WithEvents roccupation As System.Web.UI.WebControls.TextBox
    Protected WithEvents rcompany As System.Web.UI.WebControls.TextBox
    Protected WithEvents rphone As System.Web.UI.WebControls.TextBox
    Protected WithEvents hubwife As System.Web.UI.WebControls.TextBox
    Protected WithEvents hubwifeage As System.Web.UI.WebControls.TextBox
    Protected WithEvents hubicold As System.Web.UI.WebControls.TextBox
    Protected WithEvents hubicnew As System.Web.UI.WebControls.TextBox
    Protected WithEvents child1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cage1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents child2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cage2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents child3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cage3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents child4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cage4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents child5 As System.Web.UI.WebControls.TextBox
    Protected WithEvents cage5 As System.Web.UI.WebControls.TextBox
    Protected WithEvents savenext As System.Web.UI.WebControls.Button
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents CalendarExtender1 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents SqlDataSource3 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource4 As System.Web.UI.WebControls.SqlDataSource
End Class
