'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ER_letter_WizardPage
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents TextBox1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ListBox1 As System.Web.UI.WebControls.ListBox
    Protected WithEvents TextBox2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList1 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList2 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList3 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox5 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList4 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox6 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList5 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox7 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList6 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox8 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList7 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox9 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList8 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox10 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList9 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents TextBox11 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RadioButtonList10 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents Button1 As System.Web.UI.WebControls.Button
End Class
