'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4959
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class Disposal_Entry
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents dep As System.Web.UI.WebControls.Label
    Protected WithEvents items As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents control As System.Web.UI.WebControls.Label
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents availableqty As System.Web.UI.WebControls.Label
    Protected WithEvents Label4 As System.Web.UI.WebControls.Label
    Protected WithEvents dispqty As System.Web.UI.WebControls.TextBox
    Protected WithEvents Button1 As System.Web.UI.WebControls.Button
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents DISPOSALDATE As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label6 As System.Web.UI.WebControls.Label
    Protected WithEvents HRS As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator6 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents MINS As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator7 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents AMPM As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator8 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ccelt As AjaxControlToolkit.CalendarExtender
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents LblMsg As System.Web.UI.WebControls.Label
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource3 As System.Web.UI.WebControls.SqlDataSource
End Class
