'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class SchedDomWaste
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents major As System.Web.UI.WebControls.Label
    Protected WithEvents desc As System.Web.UI.WebControls.DropDownList
    Protected WithEvents view As System.Web.UI.WebControls.Button
    Protected WithEvents saveSDW As System.Web.UI.WebControls.Button
    Protected WithEvents LblMsg As System.Web.UI.WebControls.Label
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
