<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="SchedDomWaste.aspx.vb" Inherits="E_Management.SchedDomWaste" 
    title="SCHEDULE DOMESTIC WASTE CONSIGNMENT" %>
  <%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">
<table cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="16" style="height: 16px">
                <img height="16" src="../../images/top_lef.gif" width="16" /></td>
            <td background="../../images/top_mid.gif" style="height: 16px; width: 1262px;">
                <img height="16" src="../../images/top_mid.gif" width="16" /></td>
            <td style="width: 24px; height: 16px;">
                <img height="16" src="../../   images/top_rig.gif" width="24" /></td>
        </tr>
        <tr>
            <td background="../../images/cen_lef.gif" style="height: 622px" width="16">
                <img height="11" src="../../images/cen_lef.gif" width="16" /></td>
            <td bgcolor="#ffffff" style="height: 622px; width: 1262px;" valign="top">

<table style="width: 1000px; height: 145px" id="TABLE2">
        <tr>
            <td style="width: 423px;" valign="top" align="center">
                <table id="TABLE1" onclick="return TABLE1_onclick()" border="1" cellpadding="1" cellspacing="1">
                    <tr>
                        <td colspan="3" style="height: 12px" valign="top" align="left">
                        <asp:Label ID="Label1" runat="server" Font-Underline="True" ForeColor="Maroon" Text="SCHEDULE/ DOMESTIC WASTE CONSIGNMENT DETAILS"></asp:Label>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 72px; background-color: beige; height: 6px;" valign="middle" align="left">
                            <asp:Label ID="major" runat="server" Text="Major"></asp:Label></td>
                        <td style="width: 285px;" valign="middle" align="left"><asp:DropDownList ID="desc" runat="server" Width="191px" >
                            <asp:ListItem Selected="True" Value="-1">--Select--</asp:ListItem>
                            <asp:ListItem>Schedule Waste</asp:ListItem>
                            <asp:ListItem>Domestic Waste</asp:ListItem>
                        </asp:DropDownList>
                            &nbsp;&nbsp;&nbsp;</td>
                        <td align="left" style="width: 422px; height: 6px" valign="middle">
                            <asp:Button ID="view" runat="server" Text="VIEW" />
                            &nbsp;&nbsp; &nbsp;<asp:Button ID="saveSDW" runat="server" Text="SAVE" /></td>
                    </tr>
                </table>
                <asp:Label ID="LblMsg" runat="server" Font-Bold="True" Font-Size="Small" ForeColor="Green"></asp:Label>
                &nbsp;&nbsp;&nbsp;
                </td>
            <td style="width: 6100px; height: 249px;" valign="top">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4"
                    DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" Visible="False" EmptyDataText="No records found">
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <Columns>
                        <asp:BoundField DataField="item" HeaderText="item" SortExpression="item" />
                        <asp:BoundField DataField="code" HeaderText="code" SortExpression="code" />
                    </Columns>
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#999999" />
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                    SelectCommand="SELECT [item], [code] FROM [safety_temp] WHERE (([empcode] = @empcode) AND ([vdesc] = @vdesc))">
                    <SelectParameters>
                        <asp:SessionParameter Name="empcode" SessionField="empcode"
                            Type="String" />
                        <asp:ControlParameter ControlID="desc" Name="vdesc" PropertyName="SelectedValue"
                            Type="String" />
                    </SelectParameters>
                </asp:SqlDataSource>
                &nbsp;&nbsp;
            </td>
        </tr>
    </table>
    
       </td>
            <td background="../../images/cen_rig.gif" style="width: 24px">
                <img height="11" src="../../images/cen_rig.gif" width="24" /></td>
        </tr>
        <tr>
            <td height="16" width="16">
                <img height="16" src="../../images/bot_lef.gif" width="16" /></td>
            <td background="../../images/bot_mid.gif" height="16" style="width: 1262px">
                <img height="16" src="../../images/bot_mid.gif" width="16" /></td>
            <td height="16" style="width: 24px">
                <img height="16" src="../../images/bot_rig.gif" width="24" /></td>
        </tr>
    </table></asp:Content>
