'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4959
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class UOMmaster
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents oumname As System.Web.UI.WebControls.TextBox
    Protected WithEvents code As System.Web.UI.WebControls.Label
    Protected WithEvents oumcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents saveUOM As System.Web.UI.WebControls.Button
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents Label4 As System.Web.UI.WebControls.Label
    Protected WithEvents measurementname As System.Web.UI.WebControls.TextBox
    Protected WithEvents lblmsg1 As System.Web.UI.WebControls.Label
    Protected WithEvents savemeas As System.Web.UI.WebControls.Button
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents GridView2 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource3 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
