<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="Skill List.aspx.vb" Inherits="E_Management.Skill_List" 
    title="List of Skills" %>
    <%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">
    <table align="center" >
        <tr>
            <td class="td_head" colspan="2">
                LIST OF SKILLS</td>
        </tr>
        <tr>
            <td style="width: 115px">
                Skill Title</td>
            <td style="width: 316px">
                <asp:DropDownList ID="td_skilltitle" runat="server" DataSourceID="SqlDataSource1"
                    DataTextField="td_skilltitle" DataValueField="td_skilltitle" Width="191px" AutoPostBack="True" AppendDataBoundItems="True">
                    <asp:ListItem Value="-1">---Select---</asp:ListItem>
                </asp:DropDownList>
                &nbsp;&nbsp;<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="td_skilltitle"
                    ErrorMessage="TITLE !" initialvalue="-1" ValidationGroup="A"></asp:RequiredFieldValidator></td>
        </tr>
        <tr>
            <td style="width: 115px; height: 26px">
                Skill</td>
            <td align="left" style="width: 316px; height: 26px">
                <asp:TextBox ID="td_skill" runat="server" Width="185px"></asp:TextBox>&nbsp; <asp:RequiredFieldValidator
                    ID="RequiredFieldValidator3" runat="server" ControlToValidate="td_skill" ErrorMessage="SKILL !" ValidationGroup="A" ></asp:RequiredFieldValidator></td>
        </tr>
        <tr>
            <td style="width: 115px; height: 26px;">
            </td>
            <td align="center" style="width: 316px; height: 26px;">
                <asp:Button ID="btnadd" runat="server" Text="ADD" ValidationGroup="A"/></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <asp:Label ID="Label1" runat="server" Font-Size="Small" ForeColor="Maroon"></asp:Label></td>
        </tr>
        <tr>
            <td colspan="2">
                &nbsp;&nbsp;
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
                    AutoGenerateColumns="False" AutoGenerateEditButton="True"
                    CellPadding="4" DataKeyNames="td_skilltitle" DataSourceID="SqlDataSource3"
                    GridLines="None" Width="433px" AutoGenerateDeleteButton="True" >
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <Columns>
                        <asp:BoundField DataField="td_skilltitle" HeaderText="Skill Title" ReadOnly="True"
                            SortExpression="td_skilltitle" />
                        <asp:BoundField DataField="td_skill" HeaderText="Skill" SortExpression="td_skill" />
                    </Columns>
                    <FooterStyle BackColor="ActiveCaption" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#999999" />
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                    SelectCommand="SELECT DISTINCT [td_skilltitle], [td_skill] FROM [td_skilllist] ORDER BY [td_skilltitle], [td_skill]"
                    DeleteCommand = "delete from [td_skilllist] where td_skill = @td_skill and td_skilltitle = @td_skilltitle"
                    UpdateCommand = "update td_skilllist set td_skill=@td_skill where td_skilltitle=@td_skilltitle and td_skill=@td_skill">
                    <UpdateParameters>
                       <asp:Parameter Name="td_skilltitle" Type="String" />
                        <asp:Parameter Name="td_skill" Type="String" />       
                    </UpdateParameters>  
                    <%--<DELETEParameters>
                       <asp:Parameter Name="td_skilltitle" Type="String" />
                        <asp:Parameter Name="td_skill" Type="String" />       
                    </DELETEParameters>  --%>      
                </asp:SqlDataSource>
                &nbsp;
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                    SelectCommand="SELECT DISTINCT [td_title] FROM [td_trainingtitles]"></asp:SqlDataSource>
          </td>
        </tr>
    </table>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
        SelectCommand="SELECT DISTINCT [td_skilltitle] FROM [td_skillmaster]"></asp:SqlDataSource>
</asp:Content>
