<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/ems.Master" CodeBehind="group.aspx.vb" Inherits="E_Management.group" 
 Theme="buttonems" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHApplication" runat="server">
    <table style="width: 369px">
        <tr>
            <td class="td_head" colspan="2">
                GROUP MASTER</td>
        </tr>
        <tr>
            <td style="width: 62px">
                Group Code</td>
            <td style="width: 100px">
                <asp:TextBox ID="TextBox1" runat="server" Width="118px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="TextBox1"
                    ErrorMessage="Enter Group code!!!" ValidationGroup="a"></asp:RequiredFieldValidator></td>
        </tr>
        <tr>
            <td style="width: 62px">
                Group Name</td>
            <td style="width: 100px">
                <asp:TextBox ID="TextBox2" runat="server" Width="118px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBox2"
                    ErrorMessage="Enter Group Name!!!" ValidationGroup="a" Width="114px"></asp:RequiredFieldValidator></td>
        </tr>
        <tr>
            <td style="width: 62px">
            </td>
            <td align="right" style="width: 100px">
                <asp:Button ID="btnadd" runat="server" SkinID="buttonskin1" Text="ADD" ValidationGroup="a" /></td>
        </tr>
        <tr>
            <td align="left" colspan="2">
                <asp:Label ID="Label1" runat="server" Font-Size="Small" ForeColor="Maroon"></asp:Label></td>
        </tr>
        <tr>
            <td colspan="2" style="height: 440px">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True"
                    AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlGroup" ForeColor="#333333"
                    GridLines="None" PageSize="15" Width="100%" AutoGenerateDeleteButton="True" DataKeyNames="number">
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <Columns>
                        <asp:BoundField DataField="trans_groupcode" HeaderText="GroupCode" SortExpression="trans_groupcode" />
                        <asp:BoundField DataField="trans_groupname" HeaderText="GroupName" SortExpression="trans_groupname" />
                                     </Columns>
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#999999" />
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlGroup" runat="server" ConnectionString="<%$ ConnectionStrings:Sqlcon1 %>"
                    SelectCommand="SELECT [trans_groupcode], [trans_groupname],number FROM [trans_groupmaster] ORDER BY [number] desc"
                     DeleteCommand="Delete from trans_groupmaster where number=@number">
                </asp:SqlDataSource>
            </td>
        </tr>
    </table>
</asp:Content>
