'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ownvehiclamaster
    Protected WithEvents txtempcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents R4 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents lblename As System.Web.UI.WebControls.Label
    Protected WithEvents lbldept As System.Web.UI.WebControls.Label
    Protected WithEvents lblsect As System.Web.UI.WebControls.Label
    Protected WithEvents lbldesig As System.Web.UI.WebControls.Label
    Protected WithEvents txtvtype As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtvno As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtallowance As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RegularExpressionValidator1 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents btnsave As System.Web.UI.WebControls.Button
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
