'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class PickUpTimemaster
    Protected WithEvents ddlroute As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ddlarea As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ddlahr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlamin As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlaam As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlbhr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlbmin As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlbam As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlchr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlcmin As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlcam As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlmhr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlmmin As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlmam As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlnhr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlnmin As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlnam As System.Web.UI.WebControls.DropDownList
    Protected WithEvents BTNADD As System.Web.UI.WebControls.Button
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
