'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class transport_report
    Protected WithEvents grdroute As System.Web.UI.WebControls.GridView
    Protected WithEvents grdarea As System.Web.UI.WebControls.GridView
    Protected WithEvents grdarear As System.Web.UI.WebControls.GridView
    Protected WithEvents grdemp As System.Web.UI.WebControls.GridView
    Protected WithEvents grdempR As System.Web.UI.WebControls.GridView
    Protected WithEvents grdempar As System.Web.UI.WebControls.GridView
    Protected WithEvents grdsupplier As System.Web.UI.WebControls.GridView
    Protected WithEvents grdsuppR As System.Web.UI.WebControls.GridView
    Protected WithEvents grdPt As System.Web.UI.WebControls.GridView
    Protected WithEvents grdbv As System.Web.UI.WebControls.GridView
    Protected WithEvents grdownE As System.Web.UI.WebControls.GridView
    Protected WithEvents grdvehid As System.Web.UI.WebControls.GridView
    Protected WithEvents Grdvehisect As System.Web.UI.WebControls.GridView
    Protected WithEvents grdvehio As System.Web.UI.WebControls.GridView
    Protected WithEvents Sqlvehio As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlvehisect As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlvehidept As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlvehie As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlBV As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlPT As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlsuppR As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlsupplier As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlempAR As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlarea As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlemp As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlarea1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlroute As System.Web.UI.WebControls.SqlDataSource
End Class
