'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class VehicleMaster
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents Tvno As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator21 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents tcno As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator22 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents tvmodel As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator23 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents tecc As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator24 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents teno As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator25 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Dfuel As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator26 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Tseats As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator27 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RegularExpressionValidator4 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents Tcolor As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator28 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Dvcategory As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator29 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Tymodel As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator30 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RegularExpressionValidator3 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents Tvpurdate As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator31 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Ddept As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator20 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents bsave_vehicle As System.Web.UI.WebControls.Button
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents cce1 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents sqldept As System.Web.UI.WebControls.SqlDataSource
End Class
