'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4971
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class TCApproval
    Protected WithEvents rbOption As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents tdHrmis As System.Web.UI.HtmlControls.HtmlTableCell
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents txtsearch2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents ImageButton2 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents Td1 As System.Web.UI.HtmlControls.HtmlTableCell
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents txtMelaka As System.Web.UI.WebControls.TextBox
    Protected WithEvents ImageButton4 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents RequiredFieldValidator4 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents dgvmelaka As System.Web.UI.WebControls.GridView
    Protected WithEvents tdLighting As System.Web.UI.HtmlControls.HtmlTableCell
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents txtLighting As System.Web.UI.WebControls.TextBox
    Protected WithEvents ImageButton1 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents dgvLighting As System.Web.UI.WebControls.GridView
    Protected WithEvents tdMelaka As System.Web.UI.HtmlControls.HtmlTableCell
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource4 As System.Web.UI.WebControls.SqlDataSource
End Class
