'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ApptLetterLocalOptMalay
    Protected WithEvents empno As System.Web.UI.WebControls.TextBox
    Protected WithEvents V1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents dept As System.Web.UI.WebControls.Label
    Protected WithEvents ppno As System.Web.UI.WebControls.Label
    Protected WithEvents sect As System.Web.UI.WebControls.Label
    Protected WithEvents letdt As System.Web.UI.WebControls.TextBox
    Protected WithEvents R1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents frmdt As System.Web.UI.WebControls.TextBox
    Protected WithEvents R2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents todt As System.Web.UI.WebControls.TextBox
    Protected WithEvents R3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RadioButtonList1 As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents labelmsg As System.Web.UI.WebControls.Label
    Protected WithEvents ALOMsave As System.Web.UI.WebControls.Button
    Protected WithEvents fdate As AjaxControlToolkit.CalendarExtender
    Protected WithEvents tdate As AjaxControlToolkit.CalendarExtender
    Protected WithEvents letterd As AjaxControlToolkit.CalendarExtender
End Class
