'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class COntractExtensionPFPletter
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents ltdt As System.Web.UI.WebControls.Label
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents empcode As System.Web.UI.WebControls.Label
    Protected WithEvents dept As System.Web.UI.WebControls.Label
    Protected WithEvents desig As System.Web.UI.WebControls.Label
    Protected WithEvents doj As System.Web.UI.WebControls.Label
    Protected WithEvents nric As System.Web.UI.WebControls.Label
    Protected WithEvents months As System.Web.UI.WebControls.Label
    Protected WithEvents efffrom As System.Web.UI.WebControls.Label
    Protected WithEvents effto As System.Web.UI.WebControls.Label
    Protected WithEvents posall1 As System.Web.UI.WebControls.Label
    Protected WithEvents bassal As System.Web.UI.WebControls.Label
    Protected WithEvents splinc As System.Web.UI.WebControls.Label
    Protected WithEvents nbasicsal As System.Web.UI.WebControls.Label
    Protected WithEvents posall As System.Web.UI.WebControls.Label
End Class
