'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ContractExtensionLetter
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents refno As System.Web.UI.WebControls.Label
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents ltdate As System.Web.UI.WebControls.Label
    Protected WithEvents empcode As System.Web.UI.WebControls.Label
    Protected WithEvents dept As System.Web.UI.WebControls.Label
    Protected WithEvents desig As System.Web.UI.WebControls.Label
    Protected WithEvents months As System.Web.UI.WebControls.Label
    Protected WithEvents efffrom As System.Web.UI.WebControls.Label
    Protected WithEvents effto As System.Web.UI.WebControls.Label
    Protected WithEvents oldbsa As System.Web.UI.WebControls.Label
    Protected WithEvents newbsa As System.Web.UI.WebControls.Label
    Protected WithEvents oldnpa As System.Web.UI.WebControls.Label
    Protected WithEvents newnpa As System.Web.UI.WebControls.Label
    Protected WithEvents oldbsa1 As System.Web.UI.WebControls.Label
    Protected WithEvents newbsa1 As System.Web.UI.WebControls.Label
    Protected WithEvents oldnpa1 As System.Web.UI.WebControls.Label
    Protected WithEvents newnpa1 As System.Web.UI.WebControls.Label
End Class
