'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ContractExtensionWargaLetter
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents refno As System.Web.UI.WebControls.Label
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents ltdate As System.Web.UI.WebControls.Label
    Protected WithEvents empcode As System.Web.UI.WebControls.Label
    Protected WithEvents desig As System.Web.UI.WebControls.Label
    Protected WithEvents contperiod As System.Web.UI.WebControls.Label
    Protected WithEvents doj As System.Web.UI.WebControls.Label
    Protected WithEvents dteff As System.Web.UI.WebControls.Label
    Protected WithEvents extmonths As System.Web.UI.WebControls.Label
    Protected WithEvents dtfrom As System.Web.UI.WebControls.Label
    Protected WithEvents dtto As System.Web.UI.WebControls.Label
End Class
