'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class COntractExtensionTempatanLetter
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents refno As System.Web.UI.WebControls.Label
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents ltdate As System.Web.UI.WebControls.Label
    Protected WithEvents empcode As System.Web.UI.WebControls.Label
    Protected WithEvents dept As System.Web.UI.WebControls.Label
    Protected WithEvents doj As System.Web.UI.WebControls.Label
    Protected WithEvents frmdt As System.Web.UI.WebControls.Label
End Class
