'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class LetterOfCertification
    Protected WithEvents empno As System.Web.UI.WebControls.TextBox
    Protected WithEvents V1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents dept As System.Web.UI.WebControls.Label
    Protected WithEvents desig As System.Web.UI.WebControls.Label
    Protected WithEvents doj As System.Web.UI.WebControls.Label
    Protected WithEvents newicno As System.Web.UI.WebControls.Label
    Protected WithEvents letdt As System.Web.UI.WebControls.TextBox
    Protected WithEvents R5 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents labelmsg As System.Web.UI.WebControls.Label
    Protected WithEvents LoCsave As System.Web.UI.WebControls.Button
    Protected WithEvents ltdt As AjaxControlToolkit.CalendarExtender
End Class
