'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class SpecialIncentive
    Protected WithEvents empno As System.Web.UI.WebControls.TextBox
    Protected WithEvents V1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents name As System.Web.UI.WebControls.Label
    Protected WithEvents dept As System.Web.UI.WebControls.Label
    Protected WithEvents desig As System.Web.UI.WebControls.Label
    Protected WithEvents ltdt As System.Web.UI.WebControls.TextBox
    Protected WithEvents R5 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents effdt As System.Web.UI.WebControls.TextBox
    Protected WithEvents R6 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents bsa As System.Web.UI.WebControls.TextBox
    Protected WithEvents oldpall As System.Web.UI.WebControls.TextBox
    Protected WithEvents splinc As System.Web.UI.WebControls.TextBox
    Protected WithEvents nbsa As System.Web.UI.WebControls.TextBox
    Protected WithEvents pall As System.Web.UI.WebControls.TextBox
    Protected WithEvents pfpall As System.Web.UI.WebControls.TextBox
    Protected WithEvents labelmsg As System.Web.UI.WebControls.Label
    Protected WithEvents IncSPLsave As System.Web.UI.WebControls.Button
    Protected WithEvents letdate As AjaxControlToolkit.CalendarExtender
    Protected WithEvents effdate As AjaxControlToolkit.CalendarExtender
End Class
