'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class StaffForeignAppointmentLetter
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents refno As System.Web.UI.WebControls.Label
    Protected WithEvents empname1 As System.Web.UI.WebControls.Label
    Protected WithEvents age As System.Web.UI.WebControls.Label
    Protected WithEvents ldate As System.Web.UI.WebControls.Label
    Protected WithEvents desig As System.Web.UI.WebControls.Label
    Protected WithEvents deptname As System.Web.UI.WebControls.Label
    Protected WithEvents prob As System.Web.UI.WebControls.Label
    Protected WithEvents doc As System.Web.UI.WebControls.Label
    Protected WithEvents bsa As System.Web.UI.WebControls.Label
    Protected WithEvents allow As System.Web.UI.WebControls.Label
    Protected WithEvents curr As System.Web.UI.WebControls.Label
    Protected WithEvents pall As System.Web.UI.WebControls.Label
    Protected WithEvents tot As System.Web.UI.WebControls.Label
    Protected WithEvents targ As System.Web.UI.WebControls.Label
    Protected WithEvents empname As System.Web.UI.WebControls.Label
    Protected WithEvents nric As System.Web.UI.WebControls.Label
End Class
