'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class TrainingStaffLevel
    Protected WithEvents empname As System.Web.UI.WebControls.TextBox
    Protected WithEvents V1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents desig As System.Web.UI.WebControls.DropDownList
    Protected WithEvents V2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents dept As System.Web.UI.WebControls.DropDownList
    Protected WithEvents V3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents icno As System.Web.UI.WebControls.TextBox
    Protected WithEvents eff_frm As System.Web.UI.WebControls.TextBox
    Protected WithEvents V5 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents eff_to As System.Web.UI.WebControls.TextBox
    Protected WithEvents V6 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents letdt As System.Web.UI.WebControls.TextBox
    Protected WithEvents V7 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents labelmsg As System.Web.UI.WebControls.Label
    Protected WithEvents Savetrstaff As System.Web.UI.WebControls.Button
    Protected WithEvents ccelf As AjaxControlToolkit.CalendarExtender
    Protected WithEvents effrm As AjaxControlToolkit.CalendarExtender
    Protected WithEvents effto As AjaxControlToolkit.CalendarExtender
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
End Class
