'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class leaveabsentreport
    Protected WithEvents Label26 As System.Web.UI.WebControls.Label
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator10 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator11 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents cb As System.Web.UI.WebControls.CheckBox
    Protected WithEvents lbldeptr As System.Web.UI.WebControls.Label
    Protected WithEvents leavetype As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Label21 As System.Web.UI.WebControls.Label
    Protected WithEvents dept As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents TextBox1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents showtTrainingReport As System.Web.UI.WebControls.Button
    Protected WithEvents sqlsect As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDesig As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlsecdept As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents selsectreport As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource3 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents ccefrom As AjaxControlToolkit.CalendarExtender
    Protected WithEvents cceto As AjaxControlToolkit.CalendarExtender
End Class
