'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class LeaveSummary1
    Protected WithEvents Label31 As System.Web.UI.WebControls.Label
    Protected WithEvents rpttxtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents rpttxtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator15 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RequiredFieldValidator16 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents CalendarExtender3 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents CalendarExtender4 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Label33 As System.Web.UI.WebControls.Label
    Protected WithEvents rptddlltype As System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnrptsummary As System.Web.UI.WebControls.Button
End Class
