'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class RptLeaveEntitilement
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents Label37 As System.Web.UI.WebControls.Label
    Protected WithEvents rdoentby As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents Label38 As System.Web.UI.WebControls.Label
    Protected WithEvents ddlentdept As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Label39 As System.Web.UI.WebControls.Label
    Protected WithEvents ddlentdesig As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblemp As System.Web.UI.WebControls.Label
    Protected WithEvents txtempcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents btnentrpt As System.Web.UI.WebControls.Button
    Protected WithEvents SqlDesig As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
