'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class BTvisaentry
    Protected WithEvents tbtempcode As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator12 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents lblname As System.Web.UI.WebControls.Label
    Protected WithEvents lbtdept As System.Web.UI.WebControls.Label
    Protected WithEvents lbtsection As System.Web.UI.WebControls.Label
    Protected WithEvents lbtdesig As System.Web.UI.WebControls.Label
    Protected WithEvents lbtpassport As System.Web.UI.WebControls.Label
    Protected WithEvents lbtnation As System.Web.UI.WebControls.Label
    Protected WithEvents dcountry As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator13 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Dbtvisatype As System.Web.UI.WebControls.DropDownList
    Protected WithEvents DJourneytype As System.Web.UI.WebControls.DropDownList
    Protected WithEvents Tbtvisaperiod As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator14 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RegularExpressionValidator2 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents TbtVexpiry As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator15 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents bsave_btvisa As System.Web.UI.WebControls.Button
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents country As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents CalendarExtender1 As AjaxControlToolkit.CalendarExtender
End Class
