'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class CalendarMaster
    Protected WithEvents Panel1 As System.Web.UI.WebControls.Panel
    Protected WithEvents ddlgroup As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents Panel3 As System.Web.UI.WebControls.Panel
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents Panel2 As System.Web.UI.WebControls.Panel
    Protected WithEvents txtd1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator1 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls1 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator2 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls2 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd3 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator3 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls3 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd4 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator4 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls4 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd5 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator5 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls5 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd6 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator6 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls6 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd7 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator7 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls7 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd8 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator8 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls8 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtd9 As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator9 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents ddls9 As System.Web.UI.WebControls.DropDownList
    Protected WithEvents BTNSHOW As System.Web.UI.WebControls.Button
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents CalendarExtender1 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents CalendarExtender2 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource3 As System.Web.UI.WebControls.SqlDataSource
End Class
