'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class VehicleService
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents ddlvno As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents lblchasis As System.Web.UI.WebControls.Label
    Protected WithEvents lblvmodel As System.Web.UI.WebControls.Label
    Protected WithEvents lblyear As System.Web.UI.WebControls.Label
    Protected WithEvents lblcolor As System.Web.UI.WebControls.Label
    Protected WithEvents lbldate As System.Web.UI.WebControls.Label
    Protected WithEvents lblcat As System.Web.UI.WebControls.Label
    Protected WithEvents lblfuel As System.Web.UI.WebControls.Label
    Protected WithEvents txtdate As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtcentre As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtothers As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtreading1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents R3 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txtreading2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents R4 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txtitem As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator4 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RegularExpressionValidator2 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txtamt As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator6 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RegularExpressionValidator1 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txtdesc As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator5 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents btnadd As System.Web.UI.WebControls.Button
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents txtpay As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtpdate As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtcheque As System.Web.UI.WebControls.TextBox
    Protected WithEvents Button2 As System.Web.UI.WebControls.Button
    Protected WithEvents d_vehicle As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents CalendarExtender1 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents cce1 As AjaxControlToolkit.CalendarExtender
End Class
