'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ReportMajorSubKPIIndivandDept
    Protected WithEvents Panel1 As System.Web.UI.WebControls.Panel
    Protected WithEvents yearddl As System.Web.UI.WebControls.DropDownList
    Protected WithEvents optionsrb As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents txtempidr As System.Web.UI.WebControls.TextBox
    Protected WithEvents ddldeptr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnshow As System.Web.UI.WebControls.Button
    Protected WithEvents SqlDesig As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents selsectreport As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
