'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8940
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DsLeaveView"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DsLeaveView
    Inherits Global.System.Data.DataSet
    
    Private tabledtLeaveview As dtLeaveviewDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("dtLeaveview")) Is Nothing) Then
                MyBase.Tables.Add(New dtLeaveviewDataTable(ds.Tables("dtLeaveview")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property dtLeaveview() As dtLeaveviewDataTable
        Get
            Return Me.tabledtLeaveview
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DsLeaveView = CType(MyBase.Clone,DsLeaveView)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("dtLeaveview")) Is Nothing) Then
                MyBase.Tables.Add(New dtLeaveviewDataTable(ds.Tables("dtLeaveview")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tabledtLeaveview = CType(MyBase.Tables("dtLeaveview"),dtLeaveviewDataTable)
        If (initTable = true) Then
            If (Not (Me.tabledtLeaveview) Is Nothing) Then
                Me.tabledtLeaveview.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DsLeaveView"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DsLeaveView.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tabledtLeaveview = New dtLeaveviewDataTable
        MyBase.Tables.Add(Me.tabledtLeaveview)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializedtLeaveview() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DsLeaveView = New DsLeaveView
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub dtLeaveviewRowChangeEventHandler(ByVal sender As Object, ByVal e As dtLeaveviewRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class dtLeaveviewDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnAppno As Global.System.Data.DataColumn
        
        Private columnApplicationDate As Global.System.Data.DataColumn
        
        Private columnempno As Global.System.Data.DataColumn
        
        Private columnworkfor As Global.System.Data.DataColumn
        
        Private columnfromdate As Global.System.Data.DataColumn
        
        Private columntodate As Global.System.Data.DataColumn
        
        Private columnleavetype As Global.System.Data.DataColumn
        
        Private columnReason As Global.System.Data.DataColumn
        
        Private columnStatus As Global.System.Data.DataColumn
        
        Private columnEmpName As Global.System.Data.DataColumn
        
        Private columnDeptName As Global.System.Data.DataColumn
        
        Private columnSecName As Global.System.Data.DataColumn
        
        Private columnannual As Global.System.Data.DataColumn
        
        Private columnUnpaidLeave As Global.System.Data.DataColumn
        
        Private columnMaternity As Global.System.Data.DataColumn
        
        Private columnCompassionate As Global.System.Data.DataColumn
        
        Private columnMarriage As Global.System.Data.DataColumn
        
        Private columnUnpaidSick As Global.System.Data.DataColumn
        
        Private columnOthers As Global.System.Data.DataColumn
        
        Private columnApproverID As Global.System.Data.DataColumn
        
        Private columnApprovedBy As Global.System.Data.DataColumn
        
        Private columnApprovedDate As Global.System.Data.DataColumn
        
        Private columnstatusinfo As Global.System.Data.DataColumn
        
        Private columnBalanceAL As Global.System.Data.DataColumn
        
        Private columnPaternity As Global.System.Data.DataColumn
        
        Private columnSTime As Global.System.Data.DataColumn
        
        Private columnETime As Global.System.Data.DataColumn
        
        Private columnWday As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "dtLeaveview"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property AppnoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAppno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ApplicationDateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnApplicationDate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property empnoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnempno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property workforColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnworkfor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property fromdateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnfromdate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property todateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columntodate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property leavetypeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnleavetype
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ReasonColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnReason
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property StatusColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnStatus
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EmpNameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEmpName
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DeptNameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDeptName
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SecNameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSecName
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property annualColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnannual
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property UnpaidLeaveColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUnpaidLeave
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MaternityColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMaternity
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CompassionateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCompassionate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MarriageColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMarriage
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property UnpaidSickColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUnpaidSick
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property OthersColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOthers
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ApproverIDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnApproverID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ApprovedByColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnApprovedBy
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ApprovedDateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnApprovedDate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property statusinfoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnstatusinfo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BalanceALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBalanceAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PaternityColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPaternity
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property STimeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSTime
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ETimeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnETime
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property WdayColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnWday
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As dtLeaveviewRow
            Get
                Return CType(Me.Rows(index),dtLeaveviewRow)
            End Get
        End Property
        
        Public Event dtLeaveviewRowChanging As dtLeaveviewRowChangeEventHandler
        
        Public Event dtLeaveviewRowChanged As dtLeaveviewRowChangeEventHandler
        
        Public Event dtLeaveviewRowDeleting As dtLeaveviewRowChangeEventHandler
        
        Public Event dtLeaveviewRowDeleted As dtLeaveviewRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AdddtLeaveviewRow(ByVal row As dtLeaveviewRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AdddtLeaveviewRow( _
                    ByVal Appno As String,  _
                    ByVal ApplicationDate As Date,  _
                    ByVal empno As String,  _
                    ByVal workfor As Double,  _
                    ByVal fromdate As Date,  _
                    ByVal todate As Date,  _
                    ByVal leavetype As String,  _
                    ByVal Reason As String,  _
                    ByVal Status As String,  _
                    ByVal EmpName As String,  _
                    ByVal DeptName As String,  _
                    ByVal SecName As String,  _
                    ByVal annual As String,  _
                    ByVal UnpaidLeave As String,  _
                    ByVal Maternity As String,  _
                    ByVal Compassionate As String,  _
                    ByVal Marriage As String,  _
                    ByVal UnpaidSick As String,  _
                    ByVal Others As String,  _
                    ByVal ApproverID As String,  _
                    ByVal ApprovedBy As String,  _
                    ByVal ApprovedDate As Date,  _
                    ByVal statusinfo As String,  _
                    ByVal BalanceAL As Decimal,  _
                    ByVal Paternity As String,  _
                    ByVal STime As String,  _
                    ByVal ETime As String,  _
                    ByVal Wday As Decimal) As dtLeaveviewRow
            Dim rowdtLeaveviewRow As dtLeaveviewRow = CType(Me.NewRow,dtLeaveviewRow)
            Dim columnValuesArray() As Object = New Object() {Appno, ApplicationDate, empno, workfor, fromdate, todate, leavetype, Reason, Status, EmpName, DeptName, SecName, annual, UnpaidLeave, Maternity, Compassionate, Marriage, UnpaidSick, Others, ApproverID, ApprovedBy, ApprovedDate, statusinfo, BalanceAL, Paternity, STime, ETime, Wday}
            rowdtLeaveviewRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowdtLeaveviewRow)
            Return rowdtLeaveviewRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As dtLeaveviewDataTable = CType(MyBase.Clone,dtLeaveviewDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New dtLeaveviewDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnAppno = MyBase.Columns("Appno")
            Me.columnApplicationDate = MyBase.Columns("ApplicationDate")
            Me.columnempno = MyBase.Columns("empno")
            Me.columnworkfor = MyBase.Columns("workfor")
            Me.columnfromdate = MyBase.Columns("fromdate")
            Me.columntodate = MyBase.Columns("todate")
            Me.columnleavetype = MyBase.Columns("leavetype")
            Me.columnReason = MyBase.Columns("Reason")
            Me.columnStatus = MyBase.Columns("Status")
            Me.columnEmpName = MyBase.Columns("EmpName")
            Me.columnDeptName = MyBase.Columns("DeptName")
            Me.columnSecName = MyBase.Columns("SecName")
            Me.columnannual = MyBase.Columns("annual")
            Me.columnUnpaidLeave = MyBase.Columns("UnpaidLeave")
            Me.columnMaternity = MyBase.Columns("Maternity")
            Me.columnCompassionate = MyBase.Columns("Compassionate")
            Me.columnMarriage = MyBase.Columns("Marriage")
            Me.columnUnpaidSick = MyBase.Columns("UnpaidSick")
            Me.columnOthers = MyBase.Columns("Others")
            Me.columnApproverID = MyBase.Columns("ApproverID")
            Me.columnApprovedBy = MyBase.Columns("ApprovedBy")
            Me.columnApprovedDate = MyBase.Columns("ApprovedDate")
            Me.columnstatusinfo = MyBase.Columns("statusinfo")
            Me.columnBalanceAL = MyBase.Columns("BalanceAL")
            Me.columnPaternity = MyBase.Columns("Paternity")
            Me.columnSTime = MyBase.Columns("STime")
            Me.columnETime = MyBase.Columns("ETime")
            Me.columnWday = MyBase.Columns("Wday")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnAppno = New Global.System.Data.DataColumn("Appno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAppno)
            Me.columnApplicationDate = New Global.System.Data.DataColumn("ApplicationDate", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnApplicationDate)
            Me.columnempno = New Global.System.Data.DataColumn("empno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnempno)
            Me.columnworkfor = New Global.System.Data.DataColumn("workfor", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnworkfor)
            Me.columnfromdate = New Global.System.Data.DataColumn("fromdate", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnfromdate)
            Me.columntodate = New Global.System.Data.DataColumn("todate", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columntodate)
            Me.columnleavetype = New Global.System.Data.DataColumn("leavetype", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnleavetype)
            Me.columnReason = New Global.System.Data.DataColumn("Reason", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnReason)
            Me.columnStatus = New Global.System.Data.DataColumn("Status", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnStatus)
            Me.columnEmpName = New Global.System.Data.DataColumn("EmpName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEmpName)
            Me.columnDeptName = New Global.System.Data.DataColumn("DeptName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDeptName)
            Me.columnSecName = New Global.System.Data.DataColumn("SecName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSecName)
            Me.columnannual = New Global.System.Data.DataColumn("annual", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnannual)
            Me.columnUnpaidLeave = New Global.System.Data.DataColumn("UnpaidLeave", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUnpaidLeave)
            Me.columnMaternity = New Global.System.Data.DataColumn("Maternity", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMaternity)
            Me.columnCompassionate = New Global.System.Data.DataColumn("Compassionate", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCompassionate)
            Me.columnMarriage = New Global.System.Data.DataColumn("Marriage", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMarriage)
            Me.columnUnpaidSick = New Global.System.Data.DataColumn("UnpaidSick", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUnpaidSick)
            Me.columnOthers = New Global.System.Data.DataColumn("Others", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOthers)
            Me.columnApproverID = New Global.System.Data.DataColumn("ApproverID", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnApproverID)
            Me.columnApprovedBy = New Global.System.Data.DataColumn("ApprovedBy", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnApprovedBy)
            Me.columnApprovedDate = New Global.System.Data.DataColumn("ApprovedDate", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnApprovedDate)
            Me.columnstatusinfo = New Global.System.Data.DataColumn("statusinfo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnstatusinfo)
            Me.columnBalanceAL = New Global.System.Data.DataColumn("BalanceAL", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBalanceAL)
            Me.columnPaternity = New Global.System.Data.DataColumn("Paternity", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPaternity)
            Me.columnSTime = New Global.System.Data.DataColumn("STime", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSTime)
            Me.columnETime = New Global.System.Data.DataColumn("ETime", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnETime)
            Me.columnWday = New Global.System.Data.DataColumn("Wday", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnWday)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewdtLeaveviewRow() As dtLeaveviewRow
            Return CType(Me.NewRow,dtLeaveviewRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New dtLeaveviewRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(dtLeaveviewRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.dtLeaveviewRowChangedEvent) Is Nothing) Then
                RaiseEvent dtLeaveviewRowChanged(Me, New dtLeaveviewRowChangeEvent(CType(e.Row,dtLeaveviewRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.dtLeaveviewRowChangingEvent) Is Nothing) Then
                RaiseEvent dtLeaveviewRowChanging(Me, New dtLeaveviewRowChangeEvent(CType(e.Row,dtLeaveviewRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.dtLeaveviewRowDeletedEvent) Is Nothing) Then
                RaiseEvent dtLeaveviewRowDeleted(Me, New dtLeaveviewRowChangeEvent(CType(e.Row,dtLeaveviewRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.dtLeaveviewRowDeletingEvent) Is Nothing) Then
                RaiseEvent dtLeaveviewRowDeleting(Me, New dtLeaveviewRowChangeEvent(CType(e.Row,dtLeaveviewRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemovedtLeaveviewRow(ByVal row As dtLeaveviewRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DsLeaveView = New DsLeaveView
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "dtLeaveviewDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class dtLeaveviewRow
        Inherits Global.System.Data.DataRow
        
        Private tabledtLeaveview As dtLeaveviewDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tabledtLeaveview = CType(Me.Table,dtLeaveviewDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Appno() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.AppnoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Appno' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.AppnoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ApplicationDate() As Date
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.ApplicationDateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ApplicationDate' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.ApplicationDateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property empno() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.empnoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'empno' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.empnoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property workfor() As Double
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.workforColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'workfor' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.workforColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property fromdate() As Date
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.fromdateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'fromdate' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.fromdateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property todate() As Date
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.todateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'todate' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.todateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property leavetype() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.leavetypeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'leavetype' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.leavetypeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Reason() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.ReasonColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Reason' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.ReasonColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Status() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.StatusColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Status' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.StatusColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EmpName() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.EmpNameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EmpName' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.EmpNameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DeptName() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.DeptNameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DeptName' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.DeptNameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SecName() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.SecNameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SecName' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.SecNameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property annual() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.annualColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'annual' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.annualColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UnpaidLeave() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.UnpaidLeaveColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'UnpaidLeave' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.UnpaidLeaveColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Maternity() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.MaternityColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Maternity' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.MaternityColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Compassionate() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.CompassionateColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Compassionate' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.CompassionateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Marriage() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.MarriageColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Marriage' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.MarriageColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UnpaidSick() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.UnpaidSickColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'UnpaidSick' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.UnpaidSickColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Others() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.OthersColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Others' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.OthersColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ApproverID() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.ApproverIDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ApproverID' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.ApproverIDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ApprovedBy() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.ApprovedByColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ApprovedBy' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.ApprovedByColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ApprovedDate() As Date
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.ApprovedDateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ApprovedDate' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.ApprovedDateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property statusinfo() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.statusinfoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'statusinfo' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.statusinfoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BalanceAL() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.BalanceALColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BalanceAL' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.BalanceALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Paternity() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.PaternityColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Paternity' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.PaternityColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property STime() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.STimeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'STime' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.STimeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ETime() As String
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.ETimeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ETime' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.ETimeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Wday() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tabledtLeaveview.WdayColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Wday' in table 'dtLeaveview' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabledtLeaveview.WdayColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAppnoNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.AppnoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAppnoNull()
            Me(Me.tabledtLeaveview.AppnoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsApplicationDateNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.ApplicationDateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetApplicationDateNull()
            Me(Me.tabledtLeaveview.ApplicationDateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsempnoNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.empnoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetempnoNull()
            Me(Me.tabledtLeaveview.empnoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsworkforNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.workforColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetworkforNull()
            Me(Me.tabledtLeaveview.workforColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsfromdateNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.fromdateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetfromdateNull()
            Me(Me.tabledtLeaveview.fromdateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IstodateNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.todateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SettodateNull()
            Me(Me.tabledtLeaveview.todateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsleavetypeNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.leavetypeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetleavetypeNull()
            Me(Me.tabledtLeaveview.leavetypeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsReasonNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.ReasonColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetReasonNull()
            Me(Me.tabledtLeaveview.ReasonColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsStatusNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.StatusColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetStatusNull()
            Me(Me.tabledtLeaveview.StatusColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsEmpNameNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.EmpNameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetEmpNameNull()
            Me(Me.tabledtLeaveview.EmpNameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDeptNameNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.DeptNameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDeptNameNull()
            Me(Me.tabledtLeaveview.DeptNameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSecNameNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.SecNameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSecNameNull()
            Me(Me.tabledtLeaveview.SecNameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsannualNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.annualColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetannualNull()
            Me(Me.tabledtLeaveview.annualColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsUnpaidLeaveNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.UnpaidLeaveColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetUnpaidLeaveNull()
            Me(Me.tabledtLeaveview.UnpaidLeaveColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMaternityNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.MaternityColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMaternityNull()
            Me(Me.tabledtLeaveview.MaternityColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCompassionateNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.CompassionateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCompassionateNull()
            Me(Me.tabledtLeaveview.CompassionateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMarriageNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.MarriageColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMarriageNull()
            Me(Me.tabledtLeaveview.MarriageColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsUnpaidSickNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.UnpaidSickColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetUnpaidSickNull()
            Me(Me.tabledtLeaveview.UnpaidSickColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsOthersNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.OthersColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetOthersNull()
            Me(Me.tabledtLeaveview.OthersColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsApproverIDNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.ApproverIDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetApproverIDNull()
            Me(Me.tabledtLeaveview.ApproverIDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsApprovedByNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.ApprovedByColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetApprovedByNull()
            Me(Me.tabledtLeaveview.ApprovedByColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsApprovedDateNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.ApprovedDateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetApprovedDateNull()
            Me(Me.tabledtLeaveview.ApprovedDateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsstatusinfoNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.statusinfoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetstatusinfoNull()
            Me(Me.tabledtLeaveview.statusinfoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBalanceALNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.BalanceALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBalanceALNull()
            Me(Me.tabledtLeaveview.BalanceALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPaternityNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.PaternityColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPaternityNull()
            Me(Me.tabledtLeaveview.PaternityColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSTimeNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.STimeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSTimeNull()
            Me(Me.tabledtLeaveview.STimeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsETimeNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.ETimeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetETimeNull()
            Me(Me.tabledtLeaveview.ETimeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsWdayNull() As Boolean
            Return Me.IsNull(Me.tabledtLeaveview.WdayColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetWdayNull()
            Me(Me.tabledtLeaveview.WdayColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class dtLeaveviewRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As dtLeaveviewRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As dtLeaveviewRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As dtLeaveviewRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
