'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class AbnormalReplace1
    Protected WithEvents Label8 As System.Web.UI.WebControls.Label
    Protected WithEvents rbAbnormal As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents txtEmp As System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSearch As System.Web.UI.WebControls.Button
End Class
