'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class IssueBetweenDate
    Protected WithEvents Label8 As System.Web.UI.WebControls.Label
    Protected WithEvents rbtnsearch As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents txtFromDt As System.Web.UI.WebControls.TextBox
    Protected WithEvents cetxtFromDt As AjaxControlToolkit.CalendarExtender
    Protected WithEvents txtToDt As System.Web.UI.WebControls.TextBox
    Protected WithEvents cetxtToDt As AjaxControlToolkit.CalendarExtender
    Protected WithEvents rbtnType As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents ddlDept As System.Web.UI.WebControls.DropDownList
    Protected WithEvents trItem1 As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents ddlCategory As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlGroup As System.Web.UI.WebControls.DropDownList
    Protected WithEvents trItem2 As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents ddlItem As System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnSearch As System.Web.UI.WebControls.Button
End Class
