'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class clinicservice
    Protected WithEvents month As System.Web.UI.WebControls.DropDownList
    Protected WithEvents year As System.Web.UI.WebControls.DropDownList
    Protected WithEvents clinic As System.Web.UI.WebControls.DropDownList
    Protected WithEvents mc As System.Web.UI.WebControls.TextBox
    Protected WithEvents dv As System.Web.UI.WebControls.TextBox
    Protected WithEvents com As System.Web.UI.WebControls.TextBox
    Protected WithEvents save As System.Web.UI.WebControls.Button
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
End Class
