'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class contractExpiryListEA
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents Panel1 As System.Web.UI.WebControls.Panel
    Protected WithEvents rdoptions As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents lbldeptr As System.Web.UI.WebControls.Label
    Protected WithEvents ddldeptr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblsectr As System.Web.UI.WebControls.Label
    Protected WithEvents ddlsectrpt As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lbldesigr As System.Web.UI.WebControls.Label
    Protected WithEvents ddldesigr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblempr As System.Web.UI.WebControls.Label
    Protected WithEvents txtempidr As System.Web.UI.WebControls.TextBox
    Protected WithEvents btnshow As System.Web.UI.WebControls.Button
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents txtsearch2 As System.Web.UI.WebControls.TextBox
    Protected WithEvents ImageButton1 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents GridView2 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlsect As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDesig As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource3 As System.Web.UI.WebControls.SqlDataSource
End Class
