'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class reportappraisalOpt
    Protected WithEvents Label26 As System.Web.UI.WebControls.Label
    Protected WithEvents txtfrom As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtto As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator11 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents RequiredFieldValidator12 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ccefrom As AjaxControlToolkit.CalendarExtender
    Protected WithEvents cceto As AjaxControlToolkit.CalendarExtender
    Protected WithEvents Label27 As System.Web.UI.WebControls.Label
    Protected WithEvents rdoptions As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents lbldeptr As System.Web.UI.WebControls.Label
    Protected WithEvents ddldeptr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblsectr As System.Web.UI.WebControls.Label
    Protected WithEvents ddlsectrpt As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblempr As System.Web.UI.WebControls.Label
    Protected WithEvents txtempidr As System.Web.UI.WebControls.TextBox
    Protected WithEvents Button1 As System.Web.UI.WebControls.Button
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource2 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents selsectreport As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlgrid As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlsect As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDesig As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlsecdept As System.Web.UI.WebControls.SqlDataSource
End Class
