'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class AdminBt
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents GridView2 As System.Web.UI.WebControls.GridView
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SqlDataSource1 As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SqlBTFMD As System.Web.UI.WebControls.SqlDataSource
End Class
