'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class BTform
    Protected WithEvents pnlleaveform As System.Web.UI.WebControls.Panel
    Protected WithEvents lblmsg As System.Web.UI.WebControls.Label
    Protected WithEvents lbl As System.Web.UI.WebControls.Label
    Protected WithEvents lblappno As System.Web.UI.WebControls.Label
    Protected WithEvents pnl1 As System.Web.UI.WebControls.Panel
    Protected WithEvents txtpdate As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents MaskedEditExtender1 As AjaxControlToolkit.MaskedEditExtender
    Protected WithEvents MaskedEditValidator2 As AjaxControlToolkit.MaskedEditValidator
    Protected WithEvents cce1 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents txtrdate As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator2 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents MaskedEditExtender2 As AjaxControlToolkit.MaskedEditExtender
    Protected WithEvents MaskedEditValidator1 As AjaxControlToolkit.MaskedEditValidator
    Protected WithEvents CalendarExtender1 As AjaxControlToolkit.CalendarExtender
    Protected WithEvents lblduration As System.Web.UI.WebControls.Label
    Protected WithEvents txtdetails As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator3 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents lblpurpose As System.Web.UI.WebControls.Label
    Protected WithEvents ddlttype As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator4 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtdestination As System.Web.UI.WebControls.TextBox
    Protected WithEvents RequiredFieldValidator5 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ddlpurpose As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator6 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtpurpose As System.Web.UI.WebControls.TextBox
    Protected WithEvents cbgp As System.Web.UI.WebControls.CheckBox
    Protected WithEvents lbltout As System.Web.UI.WebControls.Label
    Protected WithEvents ddlohr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlomin As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddloam As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblin As System.Web.UI.WebControls.Label
    Protected WithEvents ddlihr As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlimin As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddliam As System.Web.UI.WebControls.DropDownList
    Protected WithEvents pnl2 As System.Web.UI.WebControls.Panel
    Protected WithEvents ddldept As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ddlsect As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lstcolleague As System.Web.UI.WebControls.ListBox
    Protected WithEvents btnadd As System.Web.UI.WebControls.Button
    Protected WithEvents btnremove As System.Web.UI.WebControls.Button
    Protected WithEvents lstSelcolleague As System.Web.UI.WebControls.ListBox
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents lblselect As System.Web.UI.WebControls.Label
    Protected WithEvents pnl3 As System.Web.UI.WebControls.Panel
    Protected WithEvents rbdept As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents lblshare As System.Web.UI.WebControls.Label
    Protected WithEvents lstsharedept As System.Web.UI.WebControls.ListBox
    Protected WithEvents pnl4 As System.Web.UI.WebControls.Panel
    Protected WithEvents lstcustomer As System.Web.UI.WebControls.ListBox
    Protected WithEvents lstsupplier As System.Web.UI.WebControls.ListBox
    Protected WithEvents cbcustomer As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cbsupplier As System.Web.UI.WebControls.CheckBox
    Protected WithEvents lblcust As System.Web.UI.WebControls.Label
    Protected WithEvents lblsupp As System.Web.UI.WebControls.Label
    Protected WithEvents txtnewcust As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtnewcust1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtnewsupp As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtnewsupp1 As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtcontact As System.Web.UI.WebControls.TextBox
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents lblnocust As System.Web.UI.WebControls.Label
    Protected WithEvents PNL5 As System.Web.UI.WebControls.Panel
    Protected WithEvents LblUSD As System.Web.UI.WebControls.Label
    Protected WithEvents txtamt As System.Web.UI.WebControls.TextBox
    Protected WithEvents RegularExpressionValidator1 As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txtadvance As System.Web.UI.WebControls.ListBox
    Protected WithEvents ImageButton1 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents lbltotamt As System.Web.UI.WebControls.Label
    Protected WithEvents lblusdmsg As System.Web.UI.WebControls.Label
    Protected WithEvents lblcurusd As System.Web.UI.WebControls.Label
    Protected WithEvents ddlcurrency As System.Web.UI.WebControls.DropDownList
    Protected WithEvents pnl6 As System.Web.UI.WebControls.Panel
    Protected WithEvents ddltransport As System.Web.UI.WebControls.DropDownList
    Protected WithEvents RequiredFieldValidator7 As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents rdocar As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents txtvehicle As System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlplace As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtotherplace As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtpcontact As System.Web.UI.WebControls.TextBox
    Protected WithEvents pnl9 As System.Web.UI.WebControls.Panel
    Protected WithEvents btnsave As System.Web.UI.WebControls.Button
    Protected WithEvents Sqlsect As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqlcurrency As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents Sqdept As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlcust As System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents sqlsupp As System.Web.UI.WebControls.SqlDataSource
End Class
