'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class BTSelfstatus
    Protected WithEvents GridView1 As System.Web.UI.WebControls.GridView
    Protected WithEvents SQLBT As System.Web.UI.WebControls.SqlDataSource
End Class
