'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class TCview
    Protected WithEvents Image1 As System.Web.UI.WebControls.Image
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents lbprint As System.Web.UI.WebControls.LinkButton
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents lblemp As System.Web.UI.WebControls.Label
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents lblname As System.Web.UI.WebControls.Label
    Protected WithEvents lblbt As System.Web.UI.WebControls.Label
    Protected WithEvents lblds As System.Web.UI.WebControls.Label
    Protected WithEvents tcdept As System.Web.UI.WebControls.Label
    Protected WithEvents tcname As System.Web.UI.WebControls.Label
    Protected WithEvents TCDEST As System.Web.UI.WebControls.Label
    Protected WithEvents tcpurpose As System.Web.UI.WebControls.Label
    Protected WithEvents lbldepart As System.Web.UI.WebControls.Label
    Protected WithEvents lblarrive As System.Web.UI.WebControls.Label
    Protected WithEvents lblallowance As System.Web.UI.WebControls.Label
    Protected WithEvents PlaceHolder1 As System.Web.UI.WebControls.PlaceHolder
End Class
